# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# Nome do fluxo de automação
name: Build and deploy Python app to Azure Web App - lab06software

# Gatilho: executa ao fazer push na branch main ou manualmente
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Etapa de preparação e build do projeto
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permissão de leitura do código

    steps:
      # Baixa o código do repositório
      - uses: actions/checkout@v4

      # --- NOVO STEP EXERCÍCIO 3 ---
      - name: Mensagem de inicio
        run: echo "Iniciando o deploy do meu projeto!"

      # Instala o Python 3.14 na máquina virtual
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      # Cria ambiente virtual e instala as dependências do requirements.txt
      - name: Create and Start virtual environment and Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
                
      # Sobe os arquivos para o GitHub, ignorando a pasta do ambiente virtual
      - name: Upload artifact for deployment jobs
        uses: upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  # Etapa de publicação na nuvem
  deploy:
    runs-on: ubuntu-latest
    needs: build # Só inicia se o build der certo
    
    steps:
      # Baixa os arquivos gerados no job anterior
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      # Realiza o deploy para o App Service da Azure usando o perfil de publicação
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lab06software'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37B1ACCB397148C29C632E02BE367313 }}
